language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-add-repository ppa:28msec/boost
  - sudo apt-get update
  - sudo apt-get install libboost1.50 libphysfs-dev libssl-dev liblua5.1-dev libglew1.6-dev libvorbis-dev libopenal-dev libz-dev
script: |
  cmake . -DCMAKE_BUILD_TYPE=Release
  make
notifications:
  irc:
    channels:
      - "irc.freenode.org#otclient"
    on_success: change
    skip_join: true
